# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'studyplanet' do
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => '7.1.7'
end
